# Generated by Django 6.1.1 on 2026-09-17 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(help_text='Unique roll number, e.g. 21CSE045', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Roll number may contain letters, digits, - and / only.', regex='^[A-Za-z0-9/-]+$')])),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('department', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics and Communication'), ('EEE', 'Electrical and Electronics'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering')], max_length=10)),
                ('year_of_study', models.PositiveSmallIntegerField(help_text='1 to 4', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('cgpa', models.DecimalField(decimal_places=2, help_text='0.00 to 10.00', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['roll_number'],
            },
        ),
    ]
